BOT_USERNAME = 'ReallyCoolBot'
BOT_PASSWORD = 'password'
CLIENT_ID = 'asdfasdfasdf'
CLIENT_SECRET = 'asdfasdfasdf'
DISCORD_TOKEN = 'asdfasdfasdfY'
DISCORD_ERROR_GUILD = 'SomeDiscord'
DISCORD_ERROR_CHANNEL = 'SomeDiscordChannel'
SUBREDDITS = 'SomeSubreddit,SomeOtherSubreddit'
